services:
  tasktrackr_postgres:
      image: postgres:16.3
      container_name: tasktrackr_postgres
      volumes:
        - tasktrackr_postgres_data:/var/lib/postgresql/data
      ports:
        - "5433:5432"
      environment:
        POSTGRES_DB: ${TASKTRACKR_DB}
        POSTGRES_USER: ${TASKTRACKR_USER}
        POSTGRES_PASSWORD: ${TASKTRACKR_PASSWORD}
      networks:
        - backend

  keycloak_postgres:
    image: postgres:16.3
    container_name: keycloak_postgres
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB}
      POSTGRES_USER: ${KEYCLOAK_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_PASSWORD}
    networks:
      - backend
  keycloak_tasktrackr:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak_tasktrackr
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/${KEYCLOAK_DB}
      KC_DB_USERNAME: ${KEYCLOAK_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: admin # update later
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin # update later
    command: start-dev
    ports:
      - "8180:8080"
    networks:
      - backend
  tasktrackr_app:
    build: .
    container_name: tasktrackr_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://tasktrackr_postgres:5432/${TASKTRACKR_DB}
      SPRING_DATASOURCE_USERNAME: ${TASKTRACKR_USER}
      SPRING_DATASOURCE_PASSWORD: ${TASKTRACKR_PASSWORD}
    networks:
      - backend





volumes:
  tasktrackr_postgres_data:
  keycloak_postgres_data:

networks:
  backend:
    driver: bridge

