spring:
  profiles:
      active: dev
  security:
      oauth2:
        resourceserver:
            jwt:
              issuer-uri: "http://localhost:8180/realms/tasktrackr-realm"
  jpa:
      hibernate:
        ddl-auto: none