/* flyway:transactional=false */

ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'USER_STORY_CREATED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'USER_STORY_DELETED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'USER_STORY_STATUS_UPDATED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'COMMENT_CREATED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'BLOCKER_CREATED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'BLOCKER_RESOLVED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'SPRINT_STARTED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'SPRINT_ENDED';
ALTER TYPE activity_type ADD VALUE IF NOT EXISTS 'SPRINT_CREATED';


ALTER TYPE target_type ADD VALUE IF NOT EXISTS 'SPRINT';
ALTER TYPE target_type ADD VALUE IF NOT EXISTS 'USER_STORY';
ALTER TYPE target_type ADD VALUE IF NOT EXISTS 'COMMENT';