package com.dev.tasktrackr.shared.exception;

public enum ErrorCode {
    NO_WRITE_PERMISSION,
    VALIDATION_ERROR,
    ACCESS_DENIED,
    UNAUTHORIZED,
    INTERNAL_ERROR,
    PROJECT_NOT_FOUND,
    USER_NOT_FOUND,
    PROJECT_TYPE_NOT_FOUND,
    USER_NOT_PART_OF_PROJECT,
    SENDER_ID_MISMATCH,
    INVITE_ALREADY_EXISTS,
    USER_IS_ALREADY_PART_OF_PROJECT,
    RECEIVER_ID_MISMATCH,
    INVITE_NOT_PENDING,
    INVITE_NOT_FOUND
}
